### ISSUE TITLE
Files don't always get generated?

### ISSUE THREAD

**Issue by richardshergold** [redwarp/9-Patch-Resizer#24] opened 2015-06-23 07:48 UTC
I love this tool but it does not always work.  Sometimes the files get generated and sometimes they don't.  It always says "Finished" in the Resizer Dialog but more often than not the files are not in the destination folders.  Am I doing something wrong?

**Comment by richardshergold** [comment] 2015-06-23 07:49
By the way, I think it ALWAYS works if I remove those destination folders first - but if I already have some files generated and I am just generating some more, that's when it seems to fail.

**Comment by richardshergold** [comment] 2015-06-23 08:01
Actually, thats not true.  I just deleted the target folders and dragged a set of images in.  It says Finished! against each one but no folders have been created.  I'm not sure what I am doing wrong?

**Comment by richardshergold** [comment] 2015-06-23 08:04
I just re-created a temp folder and put my images in there, then re-dragged them into Re-Sizer and it worked immediately.  Must be something to do with the target folders already existing (or previously existing) that prevents it working?

**Comment by redwarp** [comment] 2015-06-23 08:38
Hum, that's odd, I never witnessed anything like that.
What OS are you working on?

**Comment by richardshergold** [comment] 2015-06-23 08:40
OS X Yosemite.  The folder was quite embedded into my MyDocuments folder - maybe its a problem with the depth of folder nesting?  When I moved the files to a temp folder off the root it worked ok.

**Comment by redwarp** [comment] 2015-06-23 08:54
I'm on OS X Yosemite as well, I'll try to reproduce, with a deep depth. It shouldn't be a problem though. Any special chars in one of your folder names? (Which shouldn't be a problem either)

**Comment by richardshergold** [comment] 2015-06-23 08:56
No, nothing odd about the names.  I was using a depth of 4 sub-folders in.

**Comment by redwarp** [comment] 2015-06-23 08:56
But I'm pretty sure it's getting written somewhere. Otherwise, I would expect an IOException, and dipslay "error". If you look for the filename on your disk, does it pop up anywhere it shouldn't?

**Comment by richardshergold** [comment] 2015-06-23 08:57
I did look for them but couldn't find them.

**Comment by redwarp** [comment] 2015-06-23 09:01
Hum, elusive. Can't reproduce on my end... Could it be an issue with one of your images? Could you send them? (I can sign a voucher or something saying that I'm not gonna use them for anything else than testing if you want)

**Comment by richardshergold** [comment] 2015-06-23 09:03
Let me investigate a bit more and see if I can narrow things down a bit. Thanks for looking into it.

**Comment by richardshergold** [comment] 2015-06-23 09:17
Ok, this is weird.  Its a problem my end but I don't know whats causing it?  It seems that the folders were being generated but they weren't showing in Finder?  If I have a Finder window open in Search mode looking for those files it works ok every time the folders appear as I drag them across and it generates them.  If I remove the folders, close down that search window and try again, they don't show up as I generate them.  Is there some Finder Window settings that are preventing my folders from appearing immediately as they are created?  (it works some of the time!)

**Comment by redwarp** [comment] 2015-06-23 09:29
Hum, sounds weird. Is your disk almost full or something?

**Comment by richardshergold** [comment] 2015-06-23 11:57
nope - 50% free

**Comment by redwarp** [comment] 2015-06-23 12:04
I know it will sound like a line from the IT Crowd but... "Have you tried turning in off and on again?"
Cheers

**Comment by richardshergold** [comment] 2015-06-23 12:05
Yeah I have.  I have googled it and its not an uncommon problem apparently.  One trick is to right-click and do Get Info on the folder and then all the generated folders appear instantly.

**Comment by richardshergold** [comment] 2015-06-23 12:06
I guess that's why this exists http://www.macupdate.com/app/mac/24714/refresh-finder

**Comment by richardshergold** [comment] 2015-06-23 12:07
Anyway, thanks for your help - the Get Info work-around will do me fine :-)

**Comment by redwarp** [comment] 2015-06-23 12:12
I'm then closing this issue! I'm glad this app can be useful!
And if you feel that this app could be enhanced in anyway, don't hesitate to issue some suggestions (to be fair, I don't have much time to work on it currently, but it's still on my TODO list)

**Closed by redwarp** 2015-06-23 12:12 UTC
Labels: bug
